print('Tyler Annis 1/20/23')
print('Question')
print('at what size of a project should you start using version managment software?')
print('Answer')
print('you should use your version managment after the first line of code is made')
print('Question')
print('Why?')
print ('Answer')
print('it allows you to keep track of your work and ajustments')
